# Generated by Django 3.2.7 on 2021-09-26 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('translation', models.CharField(blank=True, max_length=250)),
                ('antonyms', models.ManyToManyField(blank=True, related_name='antomyms', to='words.Word')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='synonyms', to='words.Word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='words.word')),
            ],
        ),
    ]
