# Generated by Django 3.2.7 on 2021-09-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='antonyms',
            field=models.ManyToManyField(blank=True, related_name='_words_word_antonyms_+', to='words.Word'),
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='_words_word_synonyms_+', to='words.Word'),
        ),
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='Meaning',
        ),
    ]
