# Generated by Django 3.2.7 on 2021-09-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_auto_20210928_1848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('word', '-difficulty', '-updated_at')},
        ),
        migrations.AddField(
            model_name='word',
            name='frequent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
