# Generated by Django 3.2.7 on 2021-09-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_auto_20210929_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='terms_from_arts_sciences_and_social_sciences',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
