# Generated by Django 3.2.7 on 2021-09-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_auto_20210930_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='words', to='words.source'),
        ),
    ]
