# Generated by Django 3.2.7 on 2021-09-30 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_auto_20210930_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('-last_read_at', 'word', '-difficulty', '-updated_at')},
        ),
        migrations.RenameField(
            model_name='word',
            old_name='translation',
            new_name='word_translation',
        ),
        migrations.AddField(
            model_name='word',
            name='meaning_translation',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='word',
            name='source',
            field=models.ForeignKey(blank=True, default='Barron', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='words', to='words.source'),
        ),
    ]
