# Generated by Django 3.2.7 on 2021-10-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_auto_20210930_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/answers'),
        ),
    ]
