# Generated by Django 3.2.7 on 2021-10-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0013_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='unit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
