# Generated by Django 3.2.8 on 2021-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0014_auto_20211001_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='source',
        ),
        migrations.AddField(
            model_name='word',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='words', to='words.Source'),
        ),
    ]
