# Generated by Django 4.0.3 on 2022-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0017_source_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
