# Generated by Django 3.1 on 2022-12-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0018_word_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='word',
            name='antonyms',
            field=models.ManyToManyField(blank=True, related_name='_word_antonyms_+', to='words.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='_word_synonyms_+', to='words.Word'),
        ),
    ]
