# Generated by Django 3.2.7 on 2021-09-28 02:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('favourite', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('translation', models.CharField(blank=True, max_length=250)),
                ('antonyms', models.ManyToManyField(blank=True, related_name='antomyms', to='words2.Word')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='synonyms', to='words2.Word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='words2.word')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
