# Generated by Django 3.2.7 on 2021-09-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='part_of_speech',
            field=models.CharField(default='noun', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='audio_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='translation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='translation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
