# Generated by Django 3.1 on 2022-12-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words2', '0002_auto_20210928_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meaning',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='word',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
